-- Herald's v0.1 schema, complete on the first migration. Tables the
-- walking skeleton does not yet write (endpoint_secrets) ship now so
-- later cycles alter a schema instead of rebuilding one.
--
-- Identifiers are UUIDv7 generated by the application, never by the
-- database: they are time-ordered, so they cluster in B-tree indexes
-- and double as pagination cursors.
--
-- Every tenant-owned table carries tenant_id, including children that
-- could reach it through a join. Isolation is then a predicate on the
-- table being read rather than a property of the join path, and the
-- schema is ready for row-level security without a rewrite.

CREATE TABLE tenants (
  id         uuid PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Only the hash of an API key is stored: authentication hashes the
-- presented key and looks it up here, so the plaintext never has to
-- exist server-side. prefix is a short leading fragment kept purely so
-- an operator can tell two keys apart in a list.
CREATE TABLE api_keys (
  id           uuid PRIMARY KEY,
  tenant_id    uuid NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  key_hash     bytea NOT NULL UNIQUE,
  prefix       text NOT NULL,
  scope        text NOT NULL CHECK (scope IN ('full', 'ingest')),
  last_used_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX api_keys_tenant_idx ON api_keys (tenant_id, created_at DESC);

-- uid is the caller's own name for an application and is what appears
-- in URLs, so it is unique within a tenant but free to collide across
-- tenants.
CREATE TABLE applications (
  id         uuid PRIMARY KEY,
  tenant_id  uuid NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  uid        text NOT NULL,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, uid)
);

-- filter_types NULL means the endpoint wants every event type. An
-- empty array is rejected rather than treated as "none", because a
-- subscription to nothing is always a mistake and would otherwise be
-- indistinguishable from the match-all case at a glance.
CREATE TABLE endpoints (
  id             uuid PRIMARY KEY,
  tenant_id      uuid NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  application_id uuid NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
  url            text NOT NULL,
  description    text NOT NULL DEFAULT '',
  filter_types   text[] CHECK (filter_types IS NULL OR cardinality(filter_types) > 0),
  disabled       boolean NOT NULL DEFAULT false,
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- The fan-out on ingest reads exactly this set: an application's
-- endpoints that are still enabled.
CREATE INDEX endpoints_fanout_idx
  ON endpoints (tenant_id, application_id)
  WHERE NOT disabled;

-- Signing secrets. Unused until signing ships; rotation keeps the
-- outgoing secret alive until expires_at so receivers can accept both
-- during the overlap.
CREATE TABLE endpoint_secrets (
  id          uuid PRIMARY KEY,
  tenant_id   uuid NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  endpoint_id uuid NOT NULL REFERENCES endpoints (id) ON DELETE CASCADE,
  secret      bytea NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  expires_at  timestamptz
);

CREATE INDEX endpoint_secrets_endpoint_idx
  ON endpoint_secrets (tenant_id, endpoint_id, created_at DESC);

-- payload holds the bytes the tenant submitted, exactly as they were
-- submitted. It is deliberately not json or jsonb: those parse and
-- re-serialize, which reorders keys, drops duplicates and rewrites
-- whitespace, so what came back out would no longer be what came in.
-- The document is validated as JSON at ingest, which is where a caller
-- can still be told its body is unusable; from there on the bytes are
-- carried through untouched, because a signature has to cover what the
-- tenant actually sent.
CREATE TABLE messages (
  id             uuid PRIMARY KEY,
  tenant_id      uuid NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  application_id uuid NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
  event_type     text NOT NULL,
  payload        bytea NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX messages_application_idx
  ON messages (tenant_id, application_id, id DESC);

-- One row per (message, endpoint): the unit of work behind a queue job
-- and the only delivery state the API reports. The uniqueness means a
-- message can never be fanned out to the same endpoint twice.
CREATE TABLE deliveries (
  id          uuid PRIMARY KEY,
  tenant_id   uuid NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  message_id  uuid NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
  endpoint_id uuid NOT NULL REFERENCES endpoints (id) ON DELETE CASCADE,
  status      text NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'delivered', 'failed')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (message_id, endpoint_id)
);

CREATE INDEX deliveries_message_idx ON deliveries (tenant_id, message_id);
CREATE INDEX deliveries_endpoint_idx ON deliveries (tenant_id, endpoint_id, id DESC);

-- Attempts are an append-only log of what actually happened. There is
-- deliberately no uniqueness on attempt_number: if a crashed attempt is
-- re-run, that is two executions and the log says so rather than
-- pretending one of them did not happen.
--
-- status_code is NULL when no response arrived at all (timeout, refused
-- connection), which is what distinguishes a transport failure from an
-- error status.
CREATE TABLE delivery_attempts (
  id               uuid PRIMARY KEY,
  tenant_id        uuid NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
  delivery_id      uuid NOT NULL REFERENCES deliveries (id) ON DELETE CASCADE,
  attempt_number   int NOT NULL CHECK (attempt_number > 0),
  status_code      int,
  success          boolean NOT NULL,
  error            text NOT NULL DEFAULT '',
  response_snippet text NOT NULL DEFAULT '',
  duration_ms      int NOT NULL CHECK (duration_ms >= 0),
  attempted_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX delivery_attempts_delivery_idx
  ON delivery_attempts (tenant_id, delivery_id, attempted_at);
